In [132]:
import pandas as pd

In [133]:
df = pd.read_csv("D:\kepler_data.csv")

In [134]:
df

kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0     10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1     10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2     10811496  K00753.01           NaN       CANDIDATE        CANDIDATE   
3     10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4     10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   
5     10872983  K00756.01  Kepler-228 d       CONFIRMED        CANDIDATE   
6     10872983  K00756.02  Kepler-228 c       CONFIRMED        CANDIDATE   
7     10872983  K00756.03  Kepler-228 b       CONFIRMED        CANDIDATE   
8      6721123  K00114.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9     10910878  K00757.01  Kepler-229 c       CONFIRMED        CANDIDATE   
10    11446443  K00001.01    Kepler-1 b       CONFIRMED        CANDIDATE   
11    10666592  K00002.01    Kepler-2 b       CONFIRMED        CANDIDATE   
12     6922244  K00010.01    Kepler-8 b       CONFIRMED        CANDIDATE   
13    10984090  K00112.02  Kepler-466 c       CONFIRMED        CANDIDATE   
14    10419211  K00742.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
15    10464078  K00743.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
16    10480982  K00744.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
17    10485250  K00745.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
18    10526549  K00746.01  Kepler-660 b       CONFIRMED        CANDIDATE   
19    10583066  K00747.01  Kepler-661 b       CONFIRMED        CANDIDATE   
20    10583180  K00748.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
21    10601284  K00749.01  Kepler-226 c       CONFIRMED        CANDIDATE   
22    10601284  K00749.02  Kepler-226 b       CONFIRMED        CANDIDATE   
23    10601284  K00749.03  Kepler-226 d       CONFIRMED        CANDIDATE   
24     2306756  K00113.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
25    10662202  K00750.01  Kepler-662 b       CONFIRMED        CANDIDATE   
26    10682541  K00751.01  Kepler-663 b       CONFIRMED        CANDIDATE   
27    11460018  K00769.01  Kepler-671 b       CONFIRMED        CANDIDATE   
28    11463211  K00770.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
29    11465813  K00771.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
...        ...        ...           ...             ...              ...   
9534   9962731  K08191.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9535  12117215  K08296.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9536  12168280  K08297.01           NaN       CANDIDATE        CANDIDATE   
9537   9912977  K07977.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9538   9938836  K07978.01           NaN       CANDIDATE        CANDIDATE   
9539   9941425  K07979.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9540   9959368  K07980.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9541   9959765  K07981.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9542  10011213  K07982.01           NaN       CANDIDATE        CANDIDATE   
9543  10014875  K07983.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9544   3954211  K08090.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9545   4056579  K08091.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9546   4276445  K08092.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9547   4371172  K08093.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9548   4557341  K08094.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9549   4645492  K08095.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9550   4738095  K08096.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9551  10023069  K08192.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9552  10028127  K08193.01           NaN       CANDIDATE        CANDIDATE   
9553  10079317  K08194.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9554  10079481  K08195.01           NaN  FALSE POSITIVE  

In [135]:
df1 = df

In [136]:
df1

kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0     10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1     10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2     10811496  K00753.01           NaN       CANDIDATE        CANDIDATE   
3     10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4     10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   
5     10872983  K00756.01  Kepler-228 d       CONFIRMED        CANDIDATE   
6     10872983  K00756.02  Kepler-228 c       CONFIRMED        CANDIDATE   
7     10872983  K00756.03  Kepler-228 b       CONFIRMED        CANDIDATE   
8      6721123  K00114.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9     10910878  K00757.01  Kepler-229 c       CONFIRMED        CANDIDATE   
10    11446443  K00001.01    Kepler-1 b       CONFIRMED        CANDIDATE   
11    10666592  K00002.01    Kepler-2 b       CONFIRMED        CANDIDATE   
12     6922244  K00010.01    Kepler-8 b       CONFIRMED        CANDIDATE   
13    10984090  K00112.02  Kepler-466 c       CONFIRMED        CANDIDATE   
14    10419211  K00742.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
15    10464078  K00743.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
16    10480982  K00744.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
17    10485250  K00745.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
18    10526549  K00746.01  Kepler-660 b       CONFIRMED        CANDIDATE   
19    10583066  K00747.01  Kepler-661 b       CONFIRMED        CANDIDATE   
20    10583180  K00748.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
21    10601284  K00749.01  Kepler-226 c       CONFIRMED        CANDIDATE   
22    10601284  K00749.02  Kepler-226 b       CONFIRMED        CANDIDATE   
23    10601284  K00749.03  Kepler-226 d       CONFIRMED        CANDIDATE   
24     2306756  K00113.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
25    10662202  K00750.01  Kepler-662 b       CONFIRMED        CANDIDATE   
26    10682541  K00751.01  Kepler-663 b       CONFIRMED        CANDIDATE   
27    11460018  K00769.01  Kepler-671 b       CONFIRMED        CANDIDATE   
28    11463211  K00770.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
29    11465813  K00771.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
...        ...        ...           ...             ...              ...   
9534   9962731  K08191.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9535  12117215  K08296.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9536  12168280  K08297.01           NaN       CANDIDATE        CANDIDATE   
9537   9912977  K07977.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9538   9938836  K07978.01           NaN       CANDIDATE        CANDIDATE   
9539   9941425  K07979.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9540   9959368  K07980.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9541   9959765  K07981.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9542  10011213  K07982.01           NaN       CANDIDATE        CANDIDATE   
9543  10014875  K07983.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9544   3954211  K08090.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9545   4056579  K08091.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9546   4276445  K08092.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9547   4371172  K08093.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9548   4557341  K08094.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9549   4645492  K08095.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9550   4738095  K08096.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9551  10023069  K08192.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9552  10028127  K08193.01           NaN       CANDIDATE        CANDIDATE   
9553  10079317  K08194.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9554  10079481  K08195.01           NaN  FALSE POSITIVE  

Preprocessing: removal of features with string or null values

In [137]:
df1 = df1.drop(['kepid','kepoi_name','kepler_name','koi_pdisposition'],axis=1)

In [139]:
df1 = df1.drop(['koi_teq_err1','koi_teq_err2','koi_tce_delivname'],axis=1)

In [140]:
df1.shape

(9564, 42)

In [141]:
df1 = df1.dropna()

In [142]:
df1.shape

(7803, 42)

In [143]:
Y=df1['koi_disposition']

In [144]:
X = df1.drop(['koi_disposition'],axis=1)

In [145]:
X.shape

(7803, 41)

In [146]:
Y.shape

(7803,)

In [147]:
#training and testing dataset split into 75% & 25%
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [148]:
#Standardization and Normalization of dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Implementation of multiclass Support Vector Machine

In [150]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

In [151]:
clf.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [152]:
Y_pred = clf.predict(X_test)

In [154]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test,Y_pred)

[[300 151   1]
 [ 83 503   1]
 [  2   0 910]]


0.8780112762685802

Implementation of Random Forest Classifier

In [155]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state=0)
model.fit(X_train,Y_train)

C:\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [156]:
Y_pred2 = model.predict(X_test)

In [158]:
cm2 = confusion_matrix(Y_test, Y_pred2)
print(cm2)
accuracy_score(Y_test,Y_pred2)

[[329 112  11]
 [106 479   2]
 [  0   0 912]]


0.8815991799077396

In [160]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

GaussianNB(priors=None)

In [162]:
Y_pred3 = classifier.predict(X_test)

In [163]:
cm3 = confusion_matrix(Y_test, Y_pred3)
print(cm3)
accuracy_score(Y_test,Y_pred3)

[[120 322  10]
 [ 44 541   2]
 [  0  30 882]]


0.7908764736032804